// <auto-generated />
using FileDownloadHelper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FileDownloadHelper.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190613144600_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("FileDownloadHelper.Model.ImageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Datas");

                    b.HasKey("Id");

                    b.ToTable("ImageInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
